name: Prepare docker build

inputs:
  repo:
    required: true
    type: string
  tag:
    required: true
    type: string
  context:
    required: true
    type: string
  file:
    required: true
    type: string
  platforms:
    required: true
    type: string
  registry:
    required: true
    type: string
  gcp_credentials_file:
    required: true
    type: string
  gcp_project_id:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - id: checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ inputs.gcp_project_id }}
        token_format: 'access_token'
        credentials_json: ${{ inputs.gcp_credentials_file }}
        service_account: gha-436@ai-platform-prod-ade52.iam.gserviceaccount.com
    - name: 'Set up Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - uses: 'docker/login-action@v2'
      with:
        registry: ${{inputs.registry}}
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'

    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file:  ${{ inputs.file }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: |
          ${{ inputs.repo }}:${{ inputs.tag }}
          ${{ inputs.repo }}:latest

